<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;

/**
 * Class CreateDgmAttributeCategoriesTable
 *
 * Generated by ViKon\DbExporter
 */
class CreateDgmAttributeCategoriesTable extends Migration {
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up() {
        Schema::create('dgm_attribute_categories', function (Blueprint $table) {
            $table->tinyInteger('category_id')
                ->unsigned();
            $table->string('category_name', 50)
                ->nullable()
                ->default(null);
            $table->string('category_description', 200)
                ->nullable()
                ->default(null);


            $table->primary('category_id', 'prim');


        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down() {
        Schema::drop('dgm_attribute_categories');
    }
}