<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;

/**
 * Class CreateStaOperationServicesTable
 *
 * Generated by ViKon\DbExporter
 */
class CreateStaOperationServicesTable extends Migration {
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up() {
        Schema::create('sta_operation_services', function (Blueprint $table) {
            $table->tinyInteger('operation_id')
                ->unsigned();
            $table->integer('service_id');


            $table->primary(['operation_id', 'service_id'], 'prim');
            $table->index('service_id', 'service_id');


            $table->foreign('operation_id', 'sta_operation_services_ibfk_1')
                ->references('operation_id')
                ->on('sta_operations');

            $table->foreign('service_id', 'sta_operation_services_ibfk_2')
                ->references('service_id')
                ->on('sta_services');

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down() {
        Schema::drop('sta_operation_services');
    }
}