<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;

/**
 * Class CreateInvMetaTypesTable
 *
 * Generated by ViKon\DbExporter
 */
class CreateInvMetaTypesTable extends Migration {
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up() {
        Schema::create('inv_meta_types', function (Blueprint $table) {
            $table->integer('type_id');
            $table->integer('parent_type_id')
                ->nullable()
                ->default(null);
            $table->smallInteger('meta_group_id')
                ->nullable()
                ->default(null);


            $table->primary('type_id', 'prim');
            $table->index('parent_type_id', 'parent_type_id');
            $table->index('meta_group_id', 'meta_group_id');


            $table->foreign('type_id', 'inv_meta_types_ibfk_1')
                ->references('type_id')
                ->on('inv_types');

            $table->foreign('parent_type_id', 'inv_meta_types_ibfk_2')
                ->references('type_id')
                ->on('inv_types');

            $table->foreign('meta_group_id', 'inv_meta_types_ibfk_3')
                ->references('meta_group_id')
                ->on('inv_meta_groups');

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down() {
        Schema::drop('inv_meta_types');
    }
}