<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;

/**
 * Class CreateMapLandmarksTable
 *
 * Generated by ViKon\DbExporter
 */
class CreateMapLandmarksTable extends Migration {
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up() {
        Schema::create('map_landmarks', function (Blueprint $table) {
            $table->integer('landmark_id');
            $table->string('landmark_name', 100)
                ->nullable()
                ->default(null);
            $table->string('description', 7000)
                ->nullable()
                ->default(null);
            $table->integer('location_id')
                ->nullable()
                ->default(null);
            $table->float('x')
                ->nullable()
                ->default(null);
            $table->float('y')
                ->nullable()
                ->default(null);
            $table->float('z')
                ->nullable()
                ->default(null);
            $table->integer('icon_id')
                ->nullable()
                ->default(null);


            $table->primary('landmark_id', 'prim');
            $table->index('location_id', 'location_id');
            $table->index('icon_id', 'icon_id');


            $table->foreign('location_id', 'map_landmarks_ibfk_1')
                ->references('solar_system_id')
                ->on('map_solar_systems');

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down() {
        Schema::drop('map_landmarks');
    }
}