<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;

/**
 * Class AddForeignKeysToStaOperationsTable
 *
 * Generated by ViKon\DbExporter
 */
class AddForeignKeysToStaOperationsTable extends Migration {
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up() {
        Schema::table('sta_operations', function (Blueprint $table) {

            $table->foreign('activity_id', 'sta_operations_ibfk_1')
                ->references('activity_id')
                ->on('crp_activities');

            $table->foreign('caldari_station_type_id', 'sta_operations_ibfk_2')
                ->references('station_type_id')
                ->on('sta_station_types');

            $table->foreign('minmatar_station_type_id', 'sta_operations_ibfk_3')
                ->references('station_type_id')
                ->on('sta_station_types');

            $table->foreign('amarr_station_type_id', 'sta_operations_ibfk_4')
                ->references('station_type_id')
                ->on('sta_station_types');

            $table->foreign('gallente_station_type_id', 'sta_operations_ibfk_5')
                ->references('station_type_id')
                ->on('sta_station_types');

            $table->foreign('jove_station_type_id', 'sta_operations_ibfk_6')
                ->references('station_type_id')
                ->on('sta_station_types');

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down() {
        Schema::table('sta_operations', function (Blueprint $table) {

            $table->dropForeign('sta_operations_ibfk_1');
            $table->dropForeign('sta_operations_ibfk_2');
            $table->dropForeign('sta_operations_ibfk_3');
            $table->dropForeign('sta_operations_ibfk_4');
            $table->dropForeign('sta_operations_ibfk_5');
            $table->dropForeign('sta_operations_ibfk_6');
        });
    }
}