<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;

/**
 * Class AddForeignKeysToChrFactionsTable
 *
 * Generated by ViKon\DbExporter
 */
class AddForeignKeysToChrFactionsTable extends Migration {
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up() {
        Schema::table('chr_factions', function (Blueprint $table) {

            $table->foreign('solar_system_id', 'chr_factions_ibfk_1')
                ->references('solar_system_id')
                ->on('map_solar_systems');

            $table->foreign('corporation_id', 'chr_factions_ibfk_2')
                ->references('corporation_id')
                ->on('crp_n_p_c_corporations');

            $table->foreign('militia_corporation_id', 'chr_factions_ibfk_3')
                ->references('corporation_id')
                ->on('crp_n_p_c_corporations');

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down() {
        Schema::table('chr_factions', function (Blueprint $table) {

            $table->dropForeign('chr_factions_ibfk_1');
            $table->dropForeign('chr_factions_ibfk_2');
            $table->dropForeign('chr_factions_ibfk_3');
        });
    }
}