<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;

/**
 * Class CreateInvMarketGroupsTable
 *
 * Generated by ViKon\DbExporter
 */
class CreateInvMarketGroupsTable extends Migration {
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up() {
        Schema::create('inv_market_groups', function (Blueprint $table) {
            $table->integer('market_group_id');
            $table->integer('parent_group_id')
                ->nullable()
                ->default(null);
            $table->string('market_group_name', 100)
                ->nullable()
                ->default(null);
            $table->string('description', 3000)
                ->nullable()
                ->default(null);
            $table->integer('icon_id')
                ->nullable()
                ->default(null);
            $table->boolean('has_types')
                ->nullable()
                ->default(null);


            $table->primary('market_group_id', 'prim');
            $table->index('parent_group_id', 'parent_group_id');
            $table->index('icon_id', 'icon_id');


            $table->foreign('parent_group_id', 'inv_market_groups_ibfk_1')
                ->references('market_group_id')
                ->on('inv_market_groups');

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down() {
        Schema::drop('inv_market_groups');
    }
}