<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;

/**
 * Class CreateMapSolarSystemJumpsTable
 *
 * Generated by ViKon\DbExporter
 */
class CreateMapSolarSystemJumpsTable extends Migration {
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up() {
        Schema::create('map_solar_system_jumps', function (Blueprint $table) {
            $table->integer('from_region_id')
                ->nullable()
                ->default(null);
            $table->integer('from_constellation_id')
                ->nullable()
                ->default(null);
            $table->integer('from_solar_system_id');
            $table->integer('to_solar_system_id');
            $table->integer('to_constellation_id')
                ->nullable()
                ->default(null);
            $table->integer('to_region_id')
                ->nullable()
                ->default(null);


            $table->primary(['from_solar_system_id', 'to_solar_system_id'], 'prim');
            $table->index('from_region_id', 'from_region_id');
            $table->index('from_constellation_id', 'from_constellation_id');
            $table->index('to_constellation_id', 'to_constellation_id');
            $table->index('to_region_id', 'to_region_id');
            $table->index('to_solar_system_id', 'to_solar_system_id');


            $table->foreign('from_region_id', 'map_solar_system_jumps_ibfk_1')
                ->references('region_id')
                ->on('map_regions');

            $table->foreign('from_constellation_id', 'map_solar_system_jumps_ibfk_2')
                ->references('constellation_id')
                ->on('map_constellations');

            $table->foreign('from_solar_system_id', 'map_solar_system_jumps_ibfk_3')
                ->references('solar_system_id')
                ->on('map_solar_systems');

            $table->foreign('to_solar_system_id', 'map_solar_system_jumps_ibfk_4')
                ->references('solar_system_id')
                ->on('map_solar_systems');

            $table->foreign('to_constellation_id', 'map_solar_system_jumps_ibfk_5')
                ->references('constellation_id')
                ->on('map_constellations');

            $table->foreign('to_region_id', 'map_solar_system_jumps_ibfk_6')
                ->references('region_id')
                ->on('map_regions');

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down() {
        Schema::drop('map_solar_system_jumps');
    }
}