<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;

/**
 * Class CreateRamAssemblyLineTypesTable
 *
 * Generated by ViKon\DbExporter
 */
class CreateRamAssemblyLineTypesTable extends Migration {
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up() {
        Schema::create('ram_assembly_line_types', function (Blueprint $table) {
            $table->tinyInteger('assembly_line_type_id')
                ->unsigned();
            $table->string('assembly_line_type_name', 100)
                ->nullable()
                ->default(null);
            $table->string('description', 1000)
                ->nullable()
                ->default(null);
            $table->float('base_time_multiplier')
                ->nullable()
                ->default(null);
            $table->float('base_material_multiplier')
                ->nullable()
                ->default(null);
            $table->float('base_cost_multiplier')
                ->nullable()
                ->default(null);
            $table->float('volume')
                ->nullable()
                ->default(null);
            $table->tinyInteger('activity_id')
                ->unsigned()
                ->nullable()
                ->default(null);
            $table->float('min_cost_per_hour')
                ->nullable()
                ->default(null);


            $table->primary('assembly_line_type_id', 'prim');
            $table->index('activity_id', 'activity_id');


            $table->foreign('activity_id', 'ram_assembly_line_types_ibfk_1')
                ->references('activity_id')
                ->on('ram_activities');

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down() {
        Schema::drop('ram_assembly_line_types');
    }
}