<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;

/**
 * Class CreateInvControlTowerResourcesTable
 *
 * Generated by ViKon\DbExporter
 */
class CreateInvControlTowerResourcesTable extends Migration {
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up() {
        Schema::create('inv_control_tower_resources', function (Blueprint $table) {
            $table->integer('control_tower_type_id');
            $table->integer('resource_type_id');
            $table->smallInteger('purpose')
                ->nullable()
                ->default(null);
            $table->integer('quantity')
                ->nullable()
                ->default(null);
            $table->float('min_security_level')
                ->nullable()
                ->default(null);
            $table->integer('faction_id')
                ->nullable()
                ->default(null);


            $table->primary(['control_tower_type_id', 'resource_type_id'], 'prim');
            $table->index('purpose', 'purpose');
            $table->index('faction_id', 'faction_id');


            $table->foreign('control_tower_type_id', 'inv_control_tower_resources_ibfk_1')
                ->references('type_id')
                ->on('inv_types');

            $table->foreign('resource_type_id', 'inv_control_tower_resources_ibfk_2')
                ->references('type_id')
                ->on('inv_types');

            $table->foreign('purpose', 'inv_control_tower_resources_ibfk_3')
                ->references('purpose')
                ->on('inv_control_tower_resource_purposes');

            $table->foreign('faction_id', 'inv_control_tower_resources_ibfk_4')
                ->references('faction_id')
                ->on('chr_factions');

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down() {
        Schema::drop('inv_control_tower_resources');
    }
}