<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;

/**
 * Class CreateCrpNPCDivisionsTable
 *
 * Generated by ViKon\DbExporter
 */
class CreateCrpNPCDivisionsTable extends Migration {
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up() {
        Schema::create('crp_n_p_c_divisions', function (Blueprint $table) {
            $table->smallInteger('division_id');
            $table->string('division_name', 100)
                ->nullable()
                ->default(null);
            $table->string('description', 1000)
                ->nullable()
                ->default(null);
            $table->string('leader_type', 100)
                ->nullable()
                ->default(null);


            $table->primary('division_id', 'prim');


        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down() {
        Schema::drop('crp_n_p_c_divisions');
    }
}