<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;

/**
 * Class CreateDgmEffectsTable
 *
 * Generated by ViKon\DbExporter
 */
class CreateDgmEffectsTable extends Migration {
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up() {
        Schema::create('dgm_effects', function (Blueprint $table) {
            $table->smallInteger('effect_id');
            $table->string('effect_name', 400)
                ->nullable()
                ->default(null);
            $table->smallInteger('effect_category')
                ->nullable()
                ->default(null);
            $table->integer('pre_expression')
                ->nullable()
                ->default(null);
            $table->integer('post_expression')
                ->nullable()
                ->default(null);
            $table->string('description', 1000)
                ->nullable()
                ->default(null);
            $table->string('guid', 60)
                ->nullable()
                ->default(null);
            $table->integer('icon_id')
                ->nullable()
                ->default(null);
            $table->boolean('is_offensive')
                ->nullable()
                ->default(null);
            $table->boolean('is_assistance')
                ->nullable()
                ->default(null);
            $table->smallInteger('duration_attribute_id')
                ->nullable()
                ->default(null);
            $table->smallInteger('tracking_speed_attribute_id')
                ->nullable()
                ->default(null);
            $table->smallInteger('discharge_attribute_id')
                ->nullable()
                ->default(null);
            $table->smallInteger('range_attribute_id')
                ->nullable()
                ->default(null);
            $table->smallInteger('falloff_attribute_id')
                ->nullable()
                ->default(null);
            $table->boolean('disallow_auto_repeat')
                ->nullable()
                ->default(null);
            $table->boolean('published')
                ->nullable()
                ->default(null);
            $table->string('display_name', 100)
                ->nullable()
                ->default(null);
            $table->boolean('is_warp_safe')
                ->nullable()
                ->default(null);
            $table->boolean('range_chance')
                ->nullable()
                ->default(null);
            $table->boolean('electronic_chance')
                ->nullable()
                ->default(null);
            $table->boolean('propulsion_chance')
                ->nullable()
                ->default(null);
            $table->tinyInteger('distribution')
                ->unsigned()
                ->nullable()
                ->default(null);
            $table->string('sfx_name', 20)
                ->nullable()
                ->default(null);
            $table->smallInteger('npc_usage_chance_attribute_id')
                ->nullable()
                ->default(null);
            $table->smallInteger('npc_activation_chance_attribute_id')
                ->nullable()
                ->default(null);
            $table->smallInteger('fitting_usage_chance_attribute_id')
                ->nullable()
                ->default(null);
            $table->text('modifier_info')
                ->nullable()
                ->default(null);


            $table->primary('effect_id', 'prim');
            $table->index('icon_id', 'icon_id');
            $table->index('duration_attribute_id', 'duration_attribute_id');
            $table->index('tracking_speed_attribute_id', 'tracking_speed_attribute_id');
            $table->index('discharge_attribute_id', 'discharge_attribute_id');
            $table->index('range_attribute_id', 'range_attribute_id');
            $table->index('falloff_attribute_id', 'falloff_attribute_id');
            $table->index('npc_usage_chance_attribute_id', 'npc_usage_chance_attribute_id');
            $table->index('npc_activation_chance_attribute_id', 'npc_activation_chance_attribute_id');
            $table->index('fitting_usage_chance_attribute_id', 'fitting_usage_chance_attribute_id');


            $table->foreign('duration_attribute_id', 'dgm_effects_ibfk_1')
                ->references('attribute_id')
                ->on('dgm_attribute_types');

            $table->foreign('tracking_speed_attribute_id', 'dgm_effects_ibfk_2')
                ->references('attribute_id')
                ->on('dgm_attribute_types');

            $table->foreign('discharge_attribute_id', 'dgm_effects_ibfk_3')
                ->references('attribute_id')
                ->on('dgm_attribute_types');

            $table->foreign('range_attribute_id', 'dgm_effects_ibfk_4')
                ->references('attribute_id')
                ->on('dgm_attribute_types');

            $table->foreign('falloff_attribute_id', 'dgm_effects_ibfk_5')
                ->references('attribute_id')
                ->on('dgm_attribute_types');

            $table->foreign('npc_usage_chance_attribute_id', 'dgm_effects_ibfk_6')
                ->references('attribute_id')
                ->on('dgm_attribute_types');

            $table->foreign('npc_activation_chance_attribute_id', 'dgm_effects_ibfk_7')
                ->references('attribute_id')
                ->on('dgm_attribute_types');

            $table->foreign('fitting_usage_chance_attribute_id', 'dgm_effects_ibfk_8')
                ->references('attribute_id')
                ->on('dgm_attribute_types');

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down() {
        Schema::drop('dgm_effects');
    }
}