<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;

/**
 * Class CreateAgtResearchAgentsTable
 *
 * Generated by ViKon\DbExporter
 */
class CreateAgtResearchAgentsTable extends Migration {
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up() {
        Schema::create('agt_research_agents', function (Blueprint $table) {
            $table->integer('agent_id');
            $table->integer('type_id');


            $table->primary(['agent_id', 'type_id'], 'prim');
            $table->index('type_id', 'agt_research_agents__i_x_type');


            $table->foreign('agent_id', 'agt_research_agents_ibfk_1')
                ->references('agent_id')
                ->on('agt_agents');

            $table->foreign('type_id', 'agt_research_agents_ibfk_2')
                ->references('type_id')
                ->on('inv_types');

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down() {
        Schema::drop('agt_research_agents');
    }
}