<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;

/**
 * Class CreateMapSolarSystemsTable
 *
 * Generated by ViKon\DbExporter
 */
class CreateMapSolarSystemsTable extends Migration {
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up() {
        Schema::create('map_solar_systems', function (Blueprint $table) {
            $table->integer('region_id')
                ->nullable()
                ->default(null);
            $table->integer('constellation_id')
                ->nullable()
                ->default(null);
            $table->integer('solar_system_id');
            $table->string('solar_system_name', 100)
                ->nullable()
                ->default(null);
            $table->float('x')
                ->nullable()
                ->default(null);
            $table->float('y')
                ->nullable()
                ->default(null);
            $table->float('z')
                ->nullable()
                ->default(null);
            $table->float('x_min')
                ->nullable()
                ->default(null);
            $table->float('x_max')
                ->nullable()
                ->default(null);
            $table->float('y_min')
                ->nullable()
                ->default(null);
            $table->float('y_max')
                ->nullable()
                ->default(null);
            $table->float('z_min')
                ->nullable()
                ->default(null);
            $table->float('z_max')
                ->nullable()
                ->default(null);
            $table->float('luminosity')
                ->nullable()
                ->default(null);
            $table->boolean('border')
                ->nullable()
                ->default(null);
            $table->boolean('fringe')
                ->nullable()
                ->default(null);
            $table->boolean('corridor')
                ->nullable()
                ->default(null);
            $table->boolean('hub')
                ->nullable()
                ->default(null);
            $table->boolean('international')
                ->nullable()
                ->default(null);
            $table->boolean('regional')
                ->nullable()
                ->default(null);
            $table->boolean('constellation')
                ->nullable()
                ->default(null);
            $table->float('security')
                ->nullable()
                ->default(null);
            $table->integer('faction_id')
                ->nullable()
                ->default(null);
            $table->float('radius')
                ->nullable()
                ->default(null);
            $table->integer('sun_type_id')
                ->nullable()
                ->default(null);
            $table->string('security_class', 2)
                ->nullable()
                ->default(null);


            $table->primary('solar_system_id', 'prim');
            $table->index('region_id', 'map_solar_systems__i_x_region');
            $table->index('constellation_id', 'map_solar_systems__i_x_constellation');
            $table->index('security', 'map_solar_systems__i_x_security');
            $table->index('sun_type_id', 'sun_type_id');
            $table->index('faction_id', 'faction_id');


            $table->foreign('region_id', 'map_solar_systems_ibfk_1')
                ->references('region_id')
                ->on('map_regions');

            $table->foreign('constellation_id', 'map_solar_systems_ibfk_2')
                ->references('constellation_id')
                ->on('map_constellations');

            $table->foreign('sun_type_id', 'map_solar_systems_ibfk_3')
                ->references('type_id')
                ->on('inv_types');

            $table->foreign('faction_id', 'map_solar_systems_ibfk_4')
                ->references('faction_id')
                ->on('chr_factions');

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down() {
        Schema::drop('map_solar_systems');
    }
}