<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;

/**
 * Class CreateInvTypeMaterialsTable
 *
 * Generated by ViKon\DbExporter
 */
class CreateInvTypeMaterialsTable extends Migration {
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up() {
        Schema::create('inv_type_materials', function (Blueprint $table) {
            $table->integer('type_id');
            $table->integer('material_type_id');
            $table->integer('quantity');


            $table->primary(['type_id', 'material_type_id'], 'prim');
            $table->index('material_type_id', 'material_type_id');


            $table->foreign('type_id', 'inv_type_materials_ibfk_1')
                ->references('type_id')
                ->on('inv_types');

            $table->foreign('material_type_id', 'inv_type_materials_ibfk_2')
                ->references('type_id')
                ->on('inv_types');

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down() {
        Schema::drop('inv_type_materials');
    }
}