<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;

/**
 * Class CreateTrnTranslationsTable
 *
 * Generated by ViKon\DbExporter
 */
class CreateTrnTranslationsTable extends Migration {
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up() {
        Schema::create('trn_translations', function (Blueprint $table) {
            $table->smallInteger('tc_id');
            $table->integer('key_id');
            $table->string('language_id', 50);
            $table->text('text');


            $table->primary(['tc_id', 'key_id', 'language_id'], 'prim');


            $table->foreign('tc_id', 'trn_translations_ibfk_1')
                ->references('tc_id')
                ->on('trn_translation_columns');

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down() {
        Schema::drop('trn_translations');
    }
}