<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;

/**
 * Class CreateDgmAttributeTypesTable
 *
 * Generated by ViKon\DbExporter
 */
class CreateDgmAttributeTypesTable extends Migration {
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up() {
        Schema::create('dgm_attribute_types', function (Blueprint $table) {
            $table->smallInteger('attribute_id');
            $table->string('attribute_name', 100)
                ->nullable()
                ->default(null);
            $table->string('description', 1000)
                ->nullable()
                ->default(null);
            $table->integer('icon_id')
                ->nullable()
                ->default(null);
            $table->float('default_value')
                ->nullable()
                ->default(null);
            $table->boolean('published')
                ->nullable()
                ->default(null);
            $table->string('display_name', 100)
                ->nullable()
                ->default(null);
            $table->tinyInteger('unit_id')
                ->unsigned()
                ->nullable()
                ->default(null);
            $table->boolean('stackable')
                ->nullable()
                ->default(null);
            $table->boolean('high_is_good')
                ->nullable()
                ->default(null);
            $table->tinyInteger('category_id')
                ->unsigned()
                ->nullable()
                ->default(null);


            $table->primary('attribute_id', 'prim');
            $table->index('icon_id', 'icon_id');
            $table->index('unit_id', 'unit_id');
            $table->index('category_id', 'category_id');


            $table->foreign('unit_id', 'dgm_attribute_types_ibfk_1')
                ->references('unit_id')
                ->on('eve_units');

            $table->foreign('category_id', 'dgm_attribute_types_ibfk_2')
                ->references('category_id')
                ->on('dgm_attribute_categories');

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down() {
        Schema::drop('dgm_attribute_types');
    }
}