<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;

/**
 * Class CreateMapLocationScenesTable
 *
 * Generated by ViKon\DbExporter
 */
class CreateMapLocationScenesTable extends Migration {
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up() {
        Schema::create('map_location_scenes', function (Blueprint $table) {
            $table->integer('location_id');
            $table->integer('graphic_id')
                ->nullable()
                ->default(null);


            $table->primary('location_id', 'prim');
            $table->index('graphic_id', 'graphic_id');


            $table->foreign('location_id', 'map_location_scenes_ibfk_1')
                ->references('item_id')
                ->on('map_denormalize');

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down() {
        Schema::drop('map_location_scenes');
    }
}