<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;

/**
 * Class CreateInvFlagsTable
 *
 * Generated by ViKon\DbExporter
 */
class CreateInvFlagsTable extends Migration {
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up() {
        Schema::create('inv_flags', function (Blueprint $table) {
            $table->smallInteger('flag_id');
            $table->string('flag_name', 200)
                ->nullable()
                ->default(null);
            $table->string('flag_text', 100)
                ->nullable()
                ->default(null);
            $table->integer('order_id')
                ->nullable()
                ->default(null);


            $table->primary('flag_id', 'prim');
            $table->index('order_id', 'order_id');


        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down() {
        Schema::drop('inv_flags');
    }
}