<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;

/**
 * Class CreateMapConstellationJumpsTable
 *
 * Generated by ViKon\DbExporter
 */
class CreateMapConstellationJumpsTable extends Migration {
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up() {
        Schema::create('map_constellation_jumps', function (Blueprint $table) {
            $table->integer('from_region_id')
                ->nullable()
                ->default(null);
            $table->integer('from_constellation_id');
            $table->integer('to_constellation_id');
            $table->integer('to_region_id')
                ->nullable()
                ->default(null);


            $table->primary(['from_constellation_id', 'to_constellation_id'], 'prim');


        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down() {
        Schema::drop('map_constellation_jumps');
    }
}