<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;

/**
 * Class CreateInvGroupsTable
 *
 * Generated by ViKon\DbExporter
 */
class CreateInvGroupsTable extends Migration {
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up() {
        Schema::create('inv_groups', function (Blueprint $table) {
            $table->integer('group_id');
            $table->integer('category_id')
                ->nullable()
                ->default(null);
            $table->string('group_name', 100)
                ->nullable()
                ->default(null);
            $table->string('description', 3000)
                ->nullable()
                ->default(null);
            $table->integer('icon_id')
                ->nullable()
                ->default(null);
            $table->boolean('use_base_price')
                ->nullable()
                ->default(null);
            $table->boolean('allow_manufacture')
                ->nullable()
                ->default(null);
            $table->boolean('allow_recycler')
                ->nullable()
                ->default(null);
            $table->boolean('anchored')
                ->nullable()
                ->default(null);
            $table->boolean('anchorable')
                ->nullable()
                ->default(null);
            $table->boolean('fittable_non_singleton')
                ->nullable()
                ->default(null);
            $table->boolean('published')
                ->nullable()
                ->default(null);


            $table->primary('group_id', 'prim');
            $table->index('category_id', 'inv_groups__i_x_category');
            $table->index('icon_id', 'icon_id');


            $table->foreign('category_id', 'inv_groups_ibfk_1')
                ->references('category_id')
                ->on('inv_categories');

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down() {
        Schema::drop('inv_groups');
    }
}