<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;

/**
 * Class CreateChrRacesTable
 *
 * Generated by ViKon\DbExporter
 */
class CreateChrRacesTable extends Migration {
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up() {
        Schema::create('chr_races', function (Blueprint $table) {
            $table->tinyInteger('race_id')
                ->unsigned();
            $table->string('race_name', 100)
                ->nullable()
                ->default(null);
            $table->string('description', 1000)
                ->nullable()
                ->default(null);
            $table->integer('icon_id')
                ->nullable()
                ->default(null);
            $table->string('short_description', 500)
                ->nullable()
                ->default(null);


            $table->primary('race_id', 'prim');
            $table->index('icon_id', 'icon_id');


        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down() {
        Schema::drop('chr_races');
    }
}