<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;

/**
 * Class CreateMapRegionJumpsTable
 *
 * Generated by ViKon\DbExporter
 */
class CreateMapRegionJumpsTable extends Migration {
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up() {
        Schema::create('map_region_jumps', function (Blueprint $table) {
            $table->integer('from_region_id');
            $table->integer('to_region_id');


            $table->primary(['from_region_id', 'to_region_id'], 'prim');


            $table->foreign('from_region_id', 'map_region_jumps_ibfk_1')
                ->references('region_id')
                ->on('map_regions');

            $table->foreign('to_region_id', 'map_region_jumps_ibfk_2')
                ->references('region_id')
                ->on('map_regions');

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down() {
        Schema::drop('map_region_jumps');
    }
}