<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;

/**
 * Class CreateRamActivitiesTable
 *
 * Generated by ViKon\DbExporter
 */
class CreateRamActivitiesTable extends Migration {
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up() {
        Schema::create('ram_activities', function (Blueprint $table) {
            $table->smallInteger('activity_id');
            $table->string('activity_name', 100)
                ->nullable()
                ->default(null);
            $table->string('icon_no', 5)
                ->nullable()
                ->default(null);
            $table->string('description', 1000)
                ->nullable()
                ->default(null);
            $table->boolean('published')
                ->nullable()
                ->default(null);


            $table->primary('activity_id', 'prim');


        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down() {
        Schema::drop('ram_activities');
    }
}