<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;

/**
 * Class CreateInvUniqueNamesTable
 *
 * Generated by ViKon\DbExporter
 */
class CreateInvUniqueNamesTable extends Migration {
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up() {
        Schema::create('inv_unique_names', function (Blueprint $table) {
            $table->integer('item_id');
            $table->string('item_name', 200);
            $table->integer('group_id')
                ->nullable()
                ->default(null);


            $table->primary('item_id', 'prim');
            $table->unique('item_name', 'inv_unique_names__u_q');
            $table->index(['group_id', 'item_name'], 'inv_unique_names__i_x__group_name');


            $table->foreign('group_id', 'inv_unique_names_ibfk_1')
                ->references('group_id')
                ->on('inv_groups');

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down() {
        Schema::drop('inv_unique_names');
    }
}