<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;

/**
 * Class CreateInvMetaGroupsTable
 *
 * Generated by ViKon\DbExporter
 */
class CreateInvMetaGroupsTable extends Migration {
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up() {
        Schema::create('inv_meta_groups', function (Blueprint $table) {
            $table->smallInteger('meta_group_id');
            $table->string('meta_group_name', 100)
                ->nullable()
                ->default(null);
            $table->string('description', 1000)
                ->nullable()
                ->default(null);
            $table->integer('icon_id')
                ->nullable()
                ->default(null);


            $table->primary('meta_group_id', 'prim');
            $table->index('icon_id', 'icon_id');


        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down() {
        Schema::drop('inv_meta_groups');
    }
}