<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;

/**
 * Class CreateAgtAgentsTable
 *
 * Generated by ViKon\DbExporter
 */
class CreateAgtAgentsTable extends Migration {
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up() {
        Schema::create('agt_agents', function (Blueprint $table) {
            $table->integer('agent_id');
            $table->smallInteger('division_id')
                ->nullable()
                ->default(null);
            $table->integer('corporation_id')
                ->nullable()
                ->default(null);
            $table->integer('location_id')
                ->nullable()
                ->default(null);
            $table->smallInteger('level')
                ->nullable()
                ->default(null);
            $table->smallInteger('quality')
                ->nullable()
                ->default(null);
            $table->integer('agent_type_id')
                ->nullable()
                ->default(null);
            $table->boolean('is_locator')
                ->nullable()
                ->default(null);


            $table->primary('agent_id', 'prim');
            $table->index('corporation_id', 'agt_agents__i_x_corporation');
            $table->index('location_id', 'agt_agents__i_x_station');
            $table->index('division_id', 'division_id');
            $table->index('agent_type_id', 'agent_type_id');


            $table->foreign('division_id', 'agt_agents_ibfk_1')
                ->references('division_id')
                ->on('crp_n_p_c_divisions');

            $table->foreign('corporation_id', 'agt_agents_ibfk_2')
                ->references('corporation_id')
                ->on('crp_n_p_c_corporations');

            $table->foreign('agent_type_id', 'agt_agents_ibfk_3')
                ->references('agent_type_id')
                ->on('agt_agent_types');

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down() {
        Schema::drop('agt_agents');
    }
}