<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;

/**
 * Class CreateMapUniverseTable
 *
 * Generated by ViKon\DbExporter
 */
class CreateMapUniverseTable extends Migration {
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up() {
        Schema::create('map_universe', function (Blueprint $table) {
            $table->integer('universe_id');
            $table->string('universe_name', 100)
                ->nullable()
                ->default(null);
            $table->float('x')
                ->nullable()
                ->default(null);
            $table->float('y')
                ->nullable()
                ->default(null);
            $table->float('z')
                ->nullable()
                ->default(null);
            $table->float('x_min')
                ->nullable()
                ->default(null);
            $table->float('x_max')
                ->nullable()
                ->default(null);
            $table->float('y_min')
                ->nullable()
                ->default(null);
            $table->float('y_max')
                ->nullable()
                ->default(null);
            $table->float('z_min')
                ->nullable()
                ->default(null);
            $table->float('z_max')
                ->nullable()
                ->default(null);
            $table->float('radius')
                ->nullable()
                ->default(null);


            $table->primary('universe_id', 'prim');


        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down() {
        Schema::drop('map_universe');
    }
}