<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;

/**
 * Class CreateCrpNPCCorporationsTable
 *
 * Generated by ViKon\DbExporter
 */
class CreateCrpNPCCorporationsTable extends Migration {
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up() {
        Schema::create('crp_n_p_c_corporations', function (Blueprint $table) {
            $table->integer('corporation_id');
            $table->string('size', 1)
                ->nullable()
                ->default(null);
            $table->string('extent', 1)
                ->nullable()
                ->default(null);
            $table->integer('solar_system_id')
                ->nullable()
                ->default(null);
            $table->integer('investor_id1')
                ->nullable()
                ->default(null);
            $table->tinyInteger('investor_shares1')
                ->unsigned()
                ->nullable()
                ->default(null);
            $table->integer('investor_id2')
                ->nullable()
                ->default(null);
            $table->tinyInteger('investor_shares2')
                ->unsigned()
                ->nullable()
                ->default(null);
            $table->integer('investor_id3')
                ->nullable()
                ->default(null);
            $table->tinyInteger('investor_shares3')
                ->unsigned()
                ->nullable()
                ->default(null);
            $table->integer('investor_id4')
                ->nullable()
                ->default(null);
            $table->tinyInteger('investor_shares4')
                ->unsigned()
                ->nullable()
                ->default(null);
            $table->integer('friend_id')
                ->nullable()
                ->default(null);
            $table->integer('enemy_id')
                ->nullable()
                ->default(null);
            $table->bigInteger('public_shares')
                ->nullable()
                ->default(null);
            $table->integer('initial_price')
                ->nullable()
                ->default(null);
            $table->float('min_security')
                ->nullable()
                ->default(null);
            $table->boolean('scattered')
                ->nullable()
                ->default(null);
            $table->tinyInteger('fringe')
                ->unsigned()
                ->nullable()
                ->default(null);
            $table->tinyInteger('corridor')
                ->unsigned()
                ->nullable()
                ->default(null);
            $table->tinyInteger('hub')
                ->unsigned()
                ->nullable()
                ->default(null);
            $table->tinyInteger('border')
                ->unsigned()
                ->nullable()
                ->default(null);
            $table->integer('faction_id')
                ->nullable()
                ->default(null);
            $table->float('size_factor')
                ->nullable()
                ->default(null);
            $table->smallInteger('station_count')
                ->nullable()
                ->default(null);
            $table->smallInteger('station_system_count')
                ->nullable()
                ->default(null);
            $table->string('description', 4000)
                ->nullable()
                ->default(null);
            $table->integer('icon_id')
                ->nullable()
                ->default(null);


            $table->primary('corporation_id', 'prim');
            $table->index('solar_system_id', 'solar_system_id');
            $table->index('investor_id1', 'investor_id1');
            $table->index('investor_id2', 'investor_id2');
            $table->index('investor_id3', 'investor_id3');
            $table->index('investor_id4', 'investor_id4');
            $table->index('friend_id', 'friend_id');
            $table->index('enemy_id', 'enemy_id');
            $table->index('faction_id', 'faction_id');
            $table->index('icon_id', 'icon_id');


            $table->foreign('solar_system_id', 'crp_n_p_c_corporations_ibfk_1')
                ->references('solar_system_id')
                ->on('map_solar_systems');

            $table->foreign('investor_id1', 'crp_n_p_c_corporations_ibfk_2')
                ->references('corporation_id')
                ->on('crp_n_p_c_corporations');

            $table->foreign('investor_id2', 'crp_n_p_c_corporations_ibfk_3')
                ->references('corporation_id')
                ->on('crp_n_p_c_corporations');

            $table->foreign('investor_id3', 'crp_n_p_c_corporations_ibfk_4')
                ->references('corporation_id')
                ->on('crp_n_p_c_corporations');

            $table->foreign('investor_id4', 'crp_n_p_c_corporations_ibfk_5')
                ->references('corporation_id')
                ->on('crp_n_p_c_corporations');

            $table->foreign('friend_id', 'crp_n_p_c_corporations_ibfk_6')
                ->references('corporation_id')
                ->on('crp_n_p_c_corporations');

            $table->foreign('enemy_id', 'crp_n_p_c_corporations_ibfk_7')
                ->references('corporation_id')
                ->on('crp_n_p_c_corporations');

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down() {
        Schema::drop('crp_n_p_c_corporations');
    }
}