<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;

/**
 * Class CreateInvItemsTable
 *
 * Generated by ViKon\DbExporter
 */
class CreateInvItemsTable extends Migration {
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up() {
        Schema::create('inv_items', function (Blueprint $table) {
            $table->bigInteger('item_id');
            $table->integer('type_id');
            $table->integer('owner_id');
            $table->bigInteger('location_id');
            $table->smallInteger('flag_id');
            $table->integer('quantity');


            $table->primary('item_id', 'prim');
            $table->index('location_id', 'items__i_x__location');
            $table->index(['owner_id', 'location_id'], 'items__i_x__owner_location');
            $table->index('flag_id', 'flag_id');
            $table->index('type_id', 'type_id');


            $table->foreign('location_id', 'inv_items_ibfk_1')
                ->references('item_id')
                ->on('inv_items');

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down() {
        Schema::drop('inv_items');
    }
}