<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;

/**
 * Class CreateWarCombatZonesTable
 *
 * Generated by ViKon\DbExporter
 */
class CreateWarCombatZonesTable extends Migration {
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up() {
        Schema::create('war_combat_zones', function (Blueprint $table) {
            $table->integer('combat_zone_id')
                ->default('-1');
            $table->string('combat_zone_name', 100)
                ->nullable()
                ->default(null);
            $table->integer('faction_id')
                ->nullable()
                ->default(null);
            $table->integer('center_system_id')
                ->nullable()
                ->default(null);
            $table->string('description', 500)
                ->nullable()
                ->default(null);


            $table->primary('combat_zone_id', 'prim');
            $table->index('faction_id', 'faction_id');
            $table->index('center_system_id', 'center_system_id');


            $table->foreign('faction_id', 'war_combat_zones_ibfk_1')
                ->references('faction_id')
                ->on('chr_factions');

            $table->foreign('center_system_id', 'war_combat_zones_ibfk_2')
                ->references('solar_system_id')
                ->on('map_solar_systems');

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down() {
        Schema::drop('war_combat_zones');
    }
}