<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;

/**
 * Class CreateRamAssemblyLineTypeDetailPerCategoryTable
 *
 * Generated by ViKon\DbExporter
 */
class CreateRamAssemblyLineTypeDetailPerCategoryTable extends Migration {
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up() {
        Schema::create('ram_assembly_line_type_detail_per_category', function (Blueprint $table) {
            $table->tinyInteger('assembly_line_type_id')
                ->unsigned();
            $table->integer('category_id');
            $table->float('time_multiplier')
                ->nullable()
                ->default(null);
            $table->float('material_multiplier')
                ->nullable()
                ->default(null);
            $table->float('cost_multiplier')
                ->nullable()
                ->default(null);


            $table->primary(['assembly_line_type_id', 'category_id'], 'prim');
            $table->index('category_id', 'category_id');


            $table->foreign('assembly_line_type_id', 'ram_assembly_line_type_detail_per_category_ibfk_1')
                ->references('assembly_line_type_id')
                ->on('ram_assembly_line_types');

            $table->foreign('category_id', 'ram_assembly_line_type_detail_per_category_ibfk_2')
                ->references('category_id')
                ->on('inv_categories');

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down() {
        Schema::drop('ram_assembly_line_type_detail_per_category');
    }
}