<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;

/**
 * Class CreateChrFactionsTable
 *
 * Generated by ViKon\DbExporter
 */
class CreateChrFactionsTable extends Migration {
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up() {
        Schema::create('chr_factions', function (Blueprint $table) {
            $table->integer('faction_id');
            $table->string('faction_name', 100)
                ->nullable()
                ->default(null);
            $table->string('description', 1000)
                ->nullable()
                ->default(null);
            $table->integer('race_ids')
                ->nullable()
                ->default(null);
            $table->integer('solar_system_id')
                ->nullable()
                ->default(null);
            $table->integer('corporation_id')
                ->nullable()
                ->default(null);
            $table->float('size_factor')
                ->nullable()
                ->default(null);
            $table->smallInteger('station_count')
                ->nullable()
                ->default(null);
            $table->smallInteger('station_system_count')
                ->nullable()
                ->default(null);
            $table->integer('militia_corporation_id')
                ->nullable()
                ->default(null);
            $table->integer('icon_id')
                ->nullable()
                ->default(null);


            $table->primary('faction_id', 'prim');
            $table->index('solar_system_id', 'solar_system_id');
            $table->index('corporation_id', 'corporation_id');
            $table->index('militia_corporation_id', 'militia_corporation_id');
            $table->index('icon_id', 'icon_id');


        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down() {
        Schema::drop('chr_factions');
    }
}