<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;

/**
 * Class CreateRamInstallationTypeContentsTable
 *
 * Generated by ViKon\DbExporter
 */
class CreateRamInstallationTypeContentsTable extends Migration {
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up() {
        Schema::create('ram_installation_type_contents', function (Blueprint $table) {
            $table->integer('installation_type_id');
            $table->smallInteger('assembly_line_type_id');
            $table->smallInteger('quantity')
                ->nullable()
                ->default(null);


            $table->primary(['installation_type_id', 'assembly_line_type_id'], 'prim');
            $table->index('assembly_line_type_id', 'assembly_line_type_id');


            $table->foreign('assembly_line_type_id', 'ram_installation_type_contents_ibfk_1')
                ->references('assembly_line_type_id')
                ->on('ram_assembly_line_types');

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down() {
        Schema::drop('ram_installation_type_contents');
    }
}