<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;

/**
 * Class CreatePlanetSchematicsPinMapTable
 *
 * Generated by ViKon\DbExporter
 */
class CreatePlanetSchematicsPinMapTable extends Migration {
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up() {
        Schema::create('planet_schematics_pin_map', function (Blueprint $table) {
            $table->smallInteger('schematic_id');
            $table->integer('pin_type_id');


            $table->primary(['schematic_id', 'pin_type_id'], 'prim');
            $table->index('pin_type_id', 'pin_type_id');


            $table->foreign('schematic_id', 'planet_schematics_pin_map_ibfk_1')
                ->references('schematic_id')
                ->on('planet_schematics');

            $table->foreign('pin_type_id', 'planet_schematics_pin_map_ibfk_2')
                ->references('type_id')
                ->on('inv_types');

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down() {
        Schema::drop('planet_schematics_pin_map');
    }
}