<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;

/**
 * Class CreateDgmTypeEffectsTable
 *
 * Generated by ViKon\DbExporter
 */
class CreateDgmTypeEffectsTable extends Migration {
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up() {
        Schema::create('dgm_type_effects', function (Blueprint $table) {
            $table->integer('type_id');
            $table->smallInteger('effect_id');
            $table->boolean('is_default')
                ->nullable()
                ->default(null);


            $table->primary(['type_id', 'effect_id'], 'prim');


            $table->foreign('type_id', 'dgm_type_effects_ibfk_1')
                ->references('type_id')
                ->on('inv_types');

            $table->foreign('effect_id', 'dgm_type_effects_ibfk_2')
                ->references('effect_id')
                ->on('dgm_effects');

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down() {
        Schema::drop('dgm_type_effects');
    }
}