<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;

/**
 * Class CreateTrnTranslationColumnsTable
 *
 * Generated by ViKon\DbExporter
 */
class CreateTrnTranslationColumnsTable extends Migration {
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up() {
        Schema::create('trn_translation_columns', function (Blueprint $table) {
            $table->smallInteger('tc_group_id')
                ->nullable()
                ->default(null);
            $table->smallInteger('tc_id');
            $table->string('table_name', 256);
            $table->string('column_name', 128);
            $table->string('master_id', 128)
                ->nullable()
                ->default(null);


            $table->primary('tc_id', 'prim');


        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down() {
        Schema::drop('trn_translation_columns');
    }
}