<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;

/**
 * Class CreateMapJumpsTable
 *
 * Generated by ViKon\DbExporter
 */
class CreateMapJumpsTable extends Migration {
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up() {
        Schema::create('map_jumps', function (Blueprint $table) {
            $table->integer('stargate_id');
            $table->integer('destination_id')
                ->nullable()
                ->default(null);


            $table->primary('stargate_id', 'prim');
            $table->index('destination_id', 'destination_id');


            $table->foreign('stargate_id', 'map_jumps_ibfk_1')
                ->references('item_id')
                ->on('map_denormalize');

            $table->foreign('destination_id', 'map_jumps_ibfk_2')
                ->references('item_id')
                ->on('map_denormalize');

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down() {
        Schema::drop('map_jumps');
    }
}