<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;

/**
 * Class CreateStaServicesTable
 *
 * Generated by ViKon\DbExporter
 */
class CreateStaServicesTable extends Migration {
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up() {
        Schema::create('sta_services', function (Blueprint $table) {
            $table->integer('service_id');
            $table->string('service_name', 100)
                ->nullable()
                ->default(null);
            $table->string('description', 1000)
                ->nullable()
                ->default(null);


            $table->primary('service_id', 'prim');


        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down() {
        Schema::drop('sta_services');
    }
}