<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;

/**
 * Class CreatePlanetSchematicsTypeMapTable
 *
 * Generated by ViKon\DbExporter
 */
class CreatePlanetSchematicsTypeMapTable extends Migration {
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up() {
        Schema::create('planet_schematics_type_map', function (Blueprint $table) {
            $table->smallInteger('schematic_id');
            $table->integer('type_id');
            $table->smallInteger('quantity')
                ->nullable()
                ->default(null);
            $table->boolean('is_input')
                ->nullable()
                ->default(null);


            $table->primary(['schematic_id', 'type_id'], 'prim');
            $table->index('type_id', 'type_id');


            $table->foreign('schematic_id', 'planet_schematics_type_map_ibfk_1')
                ->references('schematic_id')
                ->on('planet_schematics');

            $table->foreign('type_id', 'planet_schematics_type_map_ibfk_2')
                ->references('type_id')
                ->on('inv_types');

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down() {
        Schema::drop('planet_schematics_type_map');
    }
}