<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;

/**
 * Class CreateStaOperationsTable
 *
 * Generated by ViKon\DbExporter
 */
class CreateStaOperationsTable extends Migration {
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up() {
        Schema::create('sta_operations', function (Blueprint $table) {
            $table->tinyInteger('activity_id')
                ->unsigned()
                ->nullable()
                ->default(null);
            $table->tinyInteger('operation_id')
                ->unsigned();
            $table->string('operation_name', 100)
                ->nullable()
                ->default(null);
            $table->string('description', 1000)
                ->nullable()
                ->default(null);
            $table->tinyInteger('fringe')
                ->unsigned()
                ->nullable()
                ->default(null);
            $table->tinyInteger('corridor')
                ->unsigned()
                ->nullable()
                ->default(null);
            $table->tinyInteger('hub')
                ->unsigned()
                ->nullable()
                ->default(null);
            $table->tinyInteger('border')
                ->unsigned()
                ->nullable()
                ->default(null);
            $table->tinyInteger('ratio')
                ->unsigned()
                ->nullable()
                ->default(null);
            $table->integer('caldari_station_type_id')
                ->nullable()
                ->default(null);
            $table->integer('minmatar_station_type_id')
                ->nullable()
                ->default(null);
            $table->integer('amarr_station_type_id')
                ->nullable()
                ->default(null);
            $table->integer('gallente_station_type_id')
                ->nullable()
                ->default(null);
            $table->integer('jove_station_type_id')
                ->nullable()
                ->default(null);


            $table->primary('operation_id', 'prim');
            $table->index('caldari_station_type_id', 'caldari_station_type_id');
            $table->index('minmatar_station_type_id', 'minmatar_station_type_id');
            $table->index('amarr_station_type_id', 'amarr_station_type_id');
            $table->index('gallente_station_type_id', 'gallente_station_type_id');
            $table->index('jove_station_type_id', 'jove_station_type_id');
            $table->index('activity_id', 'activity_id');


        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down() {
        Schema::drop('sta_operations');
    }
}