<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;

/**
 * Class CreateInvNamesTable
 *
 * Generated by ViKon\DbExporter
 */
class CreateInvNamesTable extends Migration {
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up() {
        Schema::create('inv_names', function (Blueprint $table) {
            $table->bigInteger('item_id');
            $table->string('item_name', 200);


            $table->primary('item_id', 'prim');


        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down() {
        Schema::drop('inv_names');
    }
}