<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;

/**
 * Class CreateMapLocationWormholeClassesTable
 *
 * Generated by ViKon\DbExporter
 */
class CreateMapLocationWormholeClassesTable extends Migration {
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up() {
        Schema::create('map_location_wormhole_classes', function (Blueprint $table) {
            $table->integer('location_id');
            $table->integer('wormhole_class_id')
                ->nullable()
                ->default(null);


            $table->primary('location_id', 'prim');


            $table->foreign('location_id', 'map_location_wormhole_classes_ibfk_1')
                ->references('item_id')
                ->on('map_denormalize');

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down() {
        Schema::drop('map_location_wormhole_classes');
    }
}