<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;

/**
 * Class CreateCrpActivitiesTable
 *
 * Generated by ViKon\DbExporter
 */
class CreateCrpActivitiesTable extends Migration {
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up() {
        Schema::create('crp_activities', function (Blueprint $table) {
            $table->tinyInteger('activity_id')
                ->unsigned();
            $table->string('activity_name', 100)
                ->nullable()
                ->default(null);
            $table->string('description', 1000)
                ->nullable()
                ->default(null);


            $table->primary('activity_id', 'prim');


        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down() {
        Schema::drop('crp_activities');
    }
}