<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;

/**
 * Class CreateTranslationTablesTable
 *
 * Generated by ViKon\DbExporter
 */
class CreateTranslationTablesTable extends Migration {
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up() {
        Schema::create('translation_tables', function (Blueprint $table) {
            $table->string('source_table', 200);
            $table->string('destination_table', 200)
                ->nullable()
                ->default(null);
            $table->string('translated_key', 200);
            $table->integer('tc_group_id')
                ->nullable()
                ->default(null);
            $table->integer('tc_id')
                ->nullable()
                ->default(null);


            $table->primary(['source_table', 'translated_key'], 'prim');
            $table->index('tc_group_id', 'tc_group_id');
            $table->index('tc_id', 'tc_id');


        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down() {
        Schema::drop('translation_tables');
    }
}