<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;

/**
 * Class CreateInvCategoriesTable
 *
 * Generated by ViKon\DbExporter
 */
class CreateInvCategoriesTable extends Migration {
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up() {
        Schema::create('inv_categories', function (Blueprint $table) {
            $table->integer('category_id');
            $table->string('category_name', 100)
                ->nullable()
                ->default(null);
            $table->string('description', 3000)
                ->nullable()
                ->default(null);
            $table->integer('icon_id')
                ->nullable()
                ->default(null);
            $table->boolean('published')
                ->nullable()
                ->default(null);


            $table->primary('category_id', 'prim');
            $table->index('icon_id', 'icon_id');


        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down() {
        Schema::drop('inv_categories');
    }
}