<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;

/**
 * Class CreateInvTypeReactionsTable
 *
 * Generated by ViKon\DbExporter
 */
class CreateInvTypeReactionsTable extends Migration {
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up() {
        Schema::create('inv_type_reactions', function (Blueprint $table) {
            $table->integer('reaction_type_id');
            $table->boolean('input');
            $table->integer('type_id');
            $table->smallInteger('quantity')
                ->nullable()
                ->default(null);


            $table->primary(['reaction_type_id', 'input', 'type_id'], 'prim');


            $table->foreign('reaction_type_id', 'inv_type_reactions_ibfk_1')
                ->references('type_id')
                ->on('inv_types');

            $table->foreign('type_id', 'inv_type_reactions_ibfk_2')
                ->references('type_id')
                ->on('inv_types');

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down() {
        Schema::drop('inv_type_reactions');
    }
}