<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;

/**
 * Class CreateCrpNPCCorporationTradesTable
 *
 * Generated by ViKon\DbExporter
 */
class CreateCrpNPCCorporationTradesTable extends Migration {
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up() {
        Schema::create('crp_n_p_c_corporation_trades', function (Blueprint $table) {
            $table->integer('corporation_id');
            $table->integer('type_id');


            $table->primary(['corporation_id', 'type_id'], 'prim');


            $table->foreign('corporation_id', 'crp_n_p_c_corporation_trades_ibfk_1')
                ->references('corporation_id')
                ->on('crp_n_p_c_corporations');

            $table->foreign('type_id', 'crp_n_p_c_corporation_trades_ibfk_2')
                ->references('type_id')
                ->on('inv_types');

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down() {
        Schema::drop('crp_n_p_c_corporation_trades');
    }
}