<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;

/**
 * Class CreateAgtAgentTypesTable
 *
 * Generated by ViKon\DbExporter
 */
class CreateAgtAgentTypesTable extends Migration {
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up() {
        Schema::create('agt_agent_types', function (Blueprint $table) {
            $table->integer('agent_type_id');
            $table->string('agent_type', 50)
                ->nullable()
                ->default(null);


            $table->primary('agent_type_id', 'prim');


        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down() {
        Schema::drop('agt_agent_types');
    }
}