<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;

/**
 * Class CreateCrpNPCCorporationDivisionsTable
 *
 * Generated by ViKon\DbExporter
 */
class CreateCrpNPCCorporationDivisionsTable extends Migration {
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up() {
        Schema::create('crp_n_p_c_corporation_divisions', function (Blueprint $table) {
            $table->integer('corporation_id');
            $table->smallInteger('division_id');
            $table->smallInteger('size')
                ->nullable()
                ->default(null);


            $table->primary(['corporation_id', 'division_id'], 'prim');


            $table->foreign('corporation_id', 'crp_n_p_c_corporation_divisions_ibfk_1')
                ->references('corporation_id')
                ->on('crp_n_p_c_corporations');

            $table->foreign('division_id', 'crp_n_p_c_corporation_divisions_ibfk_2')
                ->references('division_id')
                ->on('crp_n_p_c_divisions');

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down() {
        Schema::drop('crp_n_p_c_corporation_divisions');
    }
}