<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;

/**
 * Class CreateStaStationTypesTable
 *
 * Generated by ViKon\DbExporter
 */
class CreateStaStationTypesTable extends Migration {
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up() {
        Schema::create('sta_station_types', function (Blueprint $table) {
            $table->integer('station_type_id');
            $table->float('dock_entry_x')
                ->nullable()
                ->default(null);
            $table->float('dock_entry_y')
                ->nullable()
                ->default(null);
            $table->float('dock_entry_z')
                ->nullable()
                ->default(null);
            $table->float('dock_orientation_x')
                ->nullable()
                ->default(null);
            $table->float('dock_orientation_y')
                ->nullable()
                ->default(null);
            $table->float('dock_orientation_z')
                ->nullable()
                ->default(null);
            $table->smallInteger('operation_id')
                ->nullable()
                ->default(null);
            $table->smallInteger('office_slots')
                ->nullable()
                ->default(null);
            $table->float('reprocessing_efficiency')
                ->nullable()
                ->default(null);
            $table->boolean('conquerable')
                ->nullable()
                ->default(null);


            $table->primary('station_type_id', 'prim');
            $table->index('operation_id', 'operation_id');


            $table->foreign('station_type_id', 'sta_station_types_ibfk_1')
                ->references('type_id')
                ->on('inv_types');

            $table->foreign('operation_id', 'sta_station_types_ibfk_2')
                ->references('operation_id')
                ->on('sta_operations');

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down() {
        Schema::drop('sta_station_types');
    }
}