<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;

/**
 * Class CreateRamAssemblyLineTypeDetailPerGroupTable
 *
 * Generated by ViKon\DbExporter
 */
class CreateRamAssemblyLineTypeDetailPerGroupTable extends Migration {
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up() {
        Schema::create('ram_assembly_line_type_detail_per_group', function (Blueprint $table) {
            $table->smallInteger('assembly_line_type_id');
            $table->integer('group_id');
            $table->float('time_multiplier')
                ->nullable()
                ->default(null);
            $table->float('material_multiplier')
                ->nullable()
                ->default(null);
            $table->float('cost_multiplier')
                ->nullable()
                ->default(null);


            $table->primary(['assembly_line_type_id', 'group_id'], 'prim');


            $table->foreign('assembly_line_type_id', 'ram_assembly_line_type_detail_per_group_ibfk_1')
                ->references('assembly_line_type_id')
                ->on('ram_assembly_line_types');

            $table->foreign('group_id', 'ram_assembly_line_type_detail_per_group_ibfk_2')
                ->references('group_id')
                ->on('inv_groups');

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down() {
        Schema::drop('ram_assembly_line_type_detail_per_group');
    }
}